GET http://localhost:3001/api/notes


#### post
PUT http://localhost:3001/api/notes/69023a6b7272cb0cc82c108a
Content-Type: application/json

{
    "content": "FMC is easy",
    "important": true
}

#### Del
DELETE http://localhost:3001/api/notes/69023805b405ff901c063647
