### Get all persons
GET http://localhost:3001/api/persons

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Feto Hellas",
  "number": "050-123456"
}
